### 

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "mon@gmail.com",
  "password": "mon",
  "username": "mon"
}


### 

GET http://localhost:3000/api/auth/logout HTTP/1.1
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTc3MzgyNTQzOSwiZXhwIjoxNzc0NDMwMjM5fQ.zLEpQTNv8UXdn2PMo0_vtvhf3sNxIqRdATiMwmw2WbM


### 

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "abcd@ku.edu.np",
  "password": "asdfghjkl"
}
